### ISSUE TITLE
Настроить докерфайл и докеркомпоуз.

### ISSUE THREAD

**Issue by Sarmash** [Sarmash/FastAPI-solution#4]
Нужен Dockerfile для билда бекенда для API. Также нужно создать (или адаптировать созданные ранее) docker-compose, чтобы поднимались все сервисы разом.

**Comment by Woodsst** [comment]
https://github.com/Woodsst/new_admin_panel_sprint_3/pull/2
Изменения докер композа для  поднятия проекта целиком
