### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [Sarmash/FastAPI-solution#49]
Хорошая работа 👍
1. Предлагаю взять за правило: писать README с инструкцией по разворачиванию и запуску приложения, с указанием URL документации. Тем более, что это было одним из требований к оформлению работы.
2. Этот сервис выдачи контента, как и остальные сервисы кинотеатра, доступные пользователю, должен отдаваться через nginx.
3. В продакшене не рекомендуется запускать код через uvicorn напрямую, вот тут про это написано несколько слов https://www.uvicorn.org/deployment/#gunicorn.
4. [BaseSettings](https://pydantic-docs.helpmanual.io/usage/settings/) все делает за нас, достает и парсит переменные окружения, т.к. конфиг  `fastapi-solution/src/core/config.py` может быть таким (у pydantic-сеттингов маппинг регистронезависимый):
      ```
      class Settings(BaseSettings):
          project_name: str = 'movies'
          elasticsearch_connect: str = Field('http://localhost:9200', env='ELASTICSEARCH')
          redis_host: str = Field(..., "127.0.0.1")
          redis_port: int = Field(..., 6379)
          redis_cache_expire_in_seconds: int = 60 * 3
      ```
5. Документация ваших сервисов выглядит максимально куцей, давайте добавим хотя бы description, подробнее тут: https://fastapi.tiangolo.com/tutorial/path-operation-configuration/?h=description#summary-and-description
6. Пагинацию требуется доработать: по ТЗ к проекту требуется принимать параметры `page[size]` и `page[number]`.  https://jsonapi.org/format/#fetching-pagination
7. Текстовые сообщения, отдаваемые пользователю, (film not found) у вас расположены в разных местах кода, если появится задача добавить информативности или изменить текст сообщения, или встанет вопрос про мультиязычность, то придется по всему проекту выискивать и менять. Будет проще справиться с этой задачей, если такие сообщения будут вынесены в отдельное место в виде констант (например).
8. Во всех эндпоинтах первым параметром принимается `request: Request`, но нигде не используется. Зачем он?

**Comment by Sarmash** [comment]
Добрый день.
По поводу второго пункта issue:
Этот сервис выдачи контента, как и остальные сервисы кинотеатра, доступные пользователю, должен отдаваться через nginx.
У нас есть обработка пути через nginx, который запускается при установке контейнеров из репозитария ETL.
Не могли бы вы более конкретно указать недостаток по nginx.

**Comment by Woodsst** [comment]
8. Во всех эндпоинтах первым параметром принимается request: Request, но нигде не используется. Зачем он?

Это параметр для перехвата в декораторе кеширования, из него вынимается url запрос, который становится ключем для данных заливаемых в redis по этому запросу

**Comment by BigDeepBlue** [comment]
1. По поводу вот [такого обращения](https://github.com/Sarmash/FastAPI-solution/blob/8d6ac3973fbc0883c18cd30bd8c2e4032245b3cc/fastapi-solution/src/db/redis.py#L26) к kwargs интересная статья: https://www.codecademy.com/forum_questions/4ff4f45826304c0003000555 . Я про то, что если `request: Request` не передан, то будет выброшено исключение.

2. > Добрый день. По поводу второго пункта issue: Этот сервис выдачи контента, как и остальные сервисы кинотеатра, доступные пользователю, должен отдаваться через nginx. У нас есть обработка пути через nginx, который запускается при установке контейнеров из репозитария ETL. Не могли бы вы более конкретно указать недостаток по nginx.

      nginx не было, в README его наличие где-либо еще не было описано.
