### ISSUE TITLE
Доработать ETL для записи в ES данных жанров.

### ISSUE THREAD

**Issue by Sarmash** [Sarmash/FastAPI-solution#7]
Добавить новый ETL пайплайн, в котором создается и заполняется индекс genres из всех жанров, которые есть в фильмах. Плоский индекс без денормализованных данных. Хранить ссылки на фильмы не нужно.

**Comment by Woodsst** [comment]
https://github.com/Woodsst/new_admin_panel_sprint_3/pull/4
