### ISSUE TITLE
Доработать ETL для записи в ES данных персоналий.

### ISSUE THREAD

**Issue by Sarmash** [Sarmash/FastAPI-solution#8]
Добавить новый ETL пайплайн, в котором создается и заполняется индекс persons из всех людей, которые есть в фильмах. Плоский индекс без денормализованных данных. Хранить роли и ссылки на фильмы не нужно.

**Comment by Woodsst** [comment]
https://github.com/Woodsst/new_admin_panel_sprint_3/pull/6
